### ISSUE TITLE
Error: Invalid environment variables

### ISSUE THREAD

**Issue by Kvarkas** [Jeffreyyvdb/svelte-saas-starter#1]
PS D:\Work\AIR\Portal\next-saas-stripe-starter> npm run dev

> saas-starter@0.3.1 dev
> next dev

❌ Invalid environment variables: {
  AUTH_SECRET: [ 'Required' ],
  GOOGLE_CLIENT_ID: [ 'Required' ],
  GOOGLE_CLIENT_SECRET: [ 'Required' ],
  GITHUB_OAUTH_TOKEN: [ 'Required' ],
  DATABASE_URL: [ 'Required' ],
  RESEND_API_KEY: [ 'Required' ],
  EMAIL_FROM: [ 'Required' ],
  STRIPE_API_KEY: [ 'Required' ],
  STRIPE_WEBHOOK_SECRET: [ 'Required' ],
  NEXT_PUBLIC_APP_URL: [ 'Required' ],
  NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID: [ 'Required' ],
  NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID: [ 'Required' ],
  NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PLAN_ID: [ 'Required' ],
  NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PLAN_ID: [ 'Required' ]
}
file:///D:/Work/AIR/Portal/next-saas-stripe-starter/node_modules/@t3-oss/env-core/dist/index.js:29
        throw new Error("Invalid environment variables");
              ^

Error: Invalid environment variables
    at file:///D:/Work/AIR/Portal/next-saas-stripe-starter/node_modules/@t3-oss/env-core/dist/index.js:29:15
    at createEnv (file:///D:/Work/AIR/Portal/next-saas-stripe-starter/node_modules/@t3-oss/env-core/dist/index.js:35:16)
    at createEnv (file:///D:/Work/AIR/Portal/next-saas-stripe-starter/node_modules/@t3-oss/env-nextjs/dist/index.js:12:12)
    at file:///D:/Work/AIR/Portal/next-saas-stripe-starter/env.mjs:4:20
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)

Node.js v23.0.0

**Comment by Jeffreyyvdb** [comment]
Thank you for opening this issue!

It looks like this error is related to environment variables required by the original Next.js SaaS starter project. However, this Svelte port does not depend on the external infrastructure that would require these environment variables.

If you're looking for a solution for the original Next.js version, you may want to check that repository for guidance on setting up the required environment variables. https://github.com/mickasmt/next-saas-stripe-starter

I'll close this issue here, but please feel free to reach out if you have any questions specific to this Svelte port. Thanks again for your feedback!
